### ISSUE TITLE
logo image for Archer

### ISSUE THREAD

**Issue by csuriel** [csuriel/Archer#1]
![archer](https://cloud.githubusercontent.com/assets/8376531/15800760/31b1d184-2a50-11e6-9e64-7173456f60cd.jpg)

**Comment by wacevedo** [comment]
![image](https://cloud.githubusercontent.com/assets/11772692/16044132/235bef0c-3211-11e6-8385-3039a7a9b93e.png)

**Comment by wacevedo** [comment]
https://icons8.com/web-app/for/all/archer what you think about these icons?

**Comment by wacevedo** [comment]
![archers bow-96](https://cloud.githubusercontent.com/assets/11772692/16203696/7730ce90-36e9-11e6-93ad-f580e34d9cb0.png)
![archers bow 30](https://cloud.githubusercontent.com/assets/11772692/16203703/7d0d8826-36e9-11e6-9c88-03c94925c384.png)
![archers bow 16](https://cloud.githubusercontent.com/assets/11772692/16203709/7f6fae28-36e9-11e6-872b-654c76503166.png)

What you think?

**Comment by wacevedo** [comment]
![image](https://cloud.githubusercontent.com/assets/11772692/16231950/88f906e4-3796-11e6-8165-995df43c132c.png)
